[tool.poetry]
name = "pjmstools"
version = "0.1.0"
description = ""
authors = ["WetenSchaap <36634689+WetenSchaap@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.0"
pandas = "^2.0"
matplotlib = "^3.9.0"
scipy = "^1.14.0"
pillow = "^10.3.0"
scikit-image = "*"
pims = "^0.7"
opencv-python = "^4.0"
ruamel-yaml = "^0.18"
tifffile = "*"
tol-colors = "^2.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
